# Generated by Django 5.1.3 on 2024-12-02 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Place Name')),
                ('location', models.TextField(verbose_name='Location')),
                ('type', models.CharField(choices=[('hotel', 'Hotel'), ('attraction', 'Attraction')], max_length=50, verbose_name='Type')),
                ('is_image_file', models.BooleanField(default=True, verbose_name='Is Image File? (Unchecked for URL)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='place_images/', verbose_name='Image File')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('number_of_reviews', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('ranking', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('subcategories', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
    ]
