# Generated by Django 5.1.3 on 2024-12-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='type',
            new_name='place_type',
        ),
    ]
