# Generated by Django 5.1.3 on 2024-12-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_type_place_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='combined_amenities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
