# Generated by Django 5.1.3 on 2024-12-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_place_combined_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='ranking',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
