# Generated by Django 5.1.3 on 2024-12-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_review_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
