# Generated by Django 5.1.3 on 2024-12-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_place_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
